site_name: Gnome'un İntikamı

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Karart

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Aydınlat

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.tabbed:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - toc:
      permalink: true
  - meta

plugins:
  - search
  - roamlinks 