site_name: Gnome'un İntikamı

# Theme
theme:
    name: 'material'
    palette:

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Aydınlat

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Karart

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
  - meta

  
plugins:
  - search
  - roamlinks 
  - tags
  
  
# Extras
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js