site_name: Gnome'un İntikamı

# Theme
theme:
    name: 'material'
    custom_dir: overrides
    language: tr
    
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - announce.dismiss
      
    palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: orange

# Extensions
markdown_extensions:
  - abbr
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - meta
  - tables
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.blocks.caption
  - neoteroi.timeline
  - pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
plugins:
  - search
  - roamlinks 
  - tags
  
# Extra JS
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  
extra_css:
  - stylesheets/extra.css
  - css/neoteroi-mkdocs.css
  - stylesheets/css-v1.1.2.css